### PR TITLE
Support for embark 4-alpha.2

### PR DESCRIPTION
**Pull request by emizzle**
There were a few changes and deprecations in embark 4 that have been addressed.

### CODE REVIEW

**Comment by emizzle** [comment]
Will add ability to switch `registerConsoleCommand` signatures depending on the version...

**Comment by duaraghav8** [comment]
thanks @emizzle

**Comment by emizzle** [comment]
@duaraghav8 - this may break if used with earlier versions of embark. I am going to open a new PR with a version check and switch the implementation based on the version.

**Comment by emizzle** [comment]
https://github.com/duaraghav8/embark-solium/pull/3

**Pull request merged**
